enum PacketType {
  USER_LOGIN,
  USER_REGISTER,
  EXCEPTION,
  PING,
  USER_INFO,
  COMMON,
  PONG,
  USER_QUICK_LOGIN,
  ADD_CONTACT,
  SEND_MESSAGE_TO_CONTACT,
  PULL_SESSION,
  PUSH_OTHER_USER_CONTACT_MESSAGE,
  PUSH_OK
}
